sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js: '12'
install: yarn install
script: yarn validate
branches:
  only:
    - master
